const data = {
    products:[
        {
            _id: '1',
            name: 'Toner AR-CE285A',
            category: 'Tonner',
            image: '/images/p1.jpg',
            price: 1620,
            countInStock: 0,
            barnd: '',
            rating: 4.5,
            numReviews: 10,
            description: 'Page Yield:1600, FOR USE IN: HP LasterJet Pro P1102/P1102W M1132/M1212nf/1214nfh/1217nfw',
        },

        {
            _id: '2',
            name: 'Toner AR-CB436A',
            category: 'Tonner',
            image: '/images/p5.jpg',
            price: 2450,
            countInStock: 30,
            barnd: 'Arecolor',
            rating: 4.5,
            numReviews: 10,
            description: 'Color: Black,  Page Yield: 2000 pages,    Replaces HP CB436A, Briliant printouts ',
        },

        {
            _id: '3',
            name: 'Toner AR-CE285A',
            category: 'Tonner',
            image: '/images/p12.jpg',
            price: 1620,
            countInStock: 40,
            barnd: '',
            rating: 6.5,
            numReviews: 10,
            description: 'Page Yield:1600, FOR USE IN: HP LasterJet Pro P1102/P1102W M1132/M1212nf/1214nfh/1217nfw',
        },


        {
            _id: '4',
            name: 'Toner AR-Q7551A',
            category: 'Toner',
            image: '/images/p14.jpg',
            price: 1920,
            countInStock: 40,
            barnd: '',
            rating: 4.5,
            numReviews: 17,
            description: 'high quality product',
        },

       
        
        {
            _id: '5',
            name: 'Toner AR-Q2612A',
            category: 'Tonner',
            image: '/images/p2.jpg',
            price: 700,
            countInStock: 60,
            barnd: '',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product',
        },
        
        {
            _id: '6',
            name: 'Toner AR-CE505A',
            category: 'Toner',
            image: '/images/p6.jpg',
            price: 2080,
            countInStock: 4,
            barnd: '',
            rating: 4.5,
            numReviews: 6,
            description: 'HP Series AR-CE505A, OEM Model: CE505A, Color: black,FOR USE IN HP P2035/2035/2055N',
        },

        {
            _id: '7',
            name: 'Toner AR-CF280A',
            category: 'Tonner',
            image: '/images/p6.jpg',
            price: 2980,
            countInStock: 40,
            barnd: ': Arecolor',
            rating: 4.5,
            numReviews: 10,
            description: 'Colour:Black, Page Yield:2,700/6,900 (5%,A4), Replaces Hp CF 280A, Compatible with HP Laserjet pro M401d/M401n/M401dn/M401dw/MFP M425f/M425dn/M425dw ',
        },

        {
            _id: '8',
            name: 'HP toner CF287A',
            category: 'Toners',
            image: '/images/p8.jpg',
            price: '2100',
            countInStock: 40,
            barnd: 'Nike',
            rating: 6.5,
            numReviews:18,
            description: 'HP toner CF287A, Cartridge Colors: Black, Print Technology: Laser, Page yield: 8550,  Product type: Standard Capacity Toner Cartridges, HP LaserJet Enterprise M506 Printer series, HP LaserJet Enterprise MFP M527 series ',
        },
        {
            _id: '9',
            name: 'HP toner CF226A',
            category: 'Toners',
            image: '/images/p9.jpg',
            price: 15500,
            countInStock: 4,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'HP 26A black toner cartridge, CF226A produces superior quality and consistency for a wide array of printing needs, color Black, Yields up to 3,100 pages',
        },
        {
            _id: '10',
            name: 'HP Toner CF217A Black',
            category: 'Tonner',
            image: '/images/p10.jpg',
            price: 8600,
            countInStock: 40,
            barnd: 'hp',
            rating: 4.5,
            numReviews: 10,
            description: 'color: black, Print technology: laser, Approximate average yield based on ISO/IEC 19752. Actual yield varies considerably based on content of printed pages and other factors. ',
        },
        {
            _id: '11',
            name: 'Toner AR-CF230A',
            category: 'Toner',
            image: '/images/p11.jpg',
            price: 3470,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'HP Series AR-CF230A, OEM Model:CF230A, Color: Black, FOR USE IN: HP LaserJet M203d/203dn/203dw/M227fdn/227fdw, Page Yield ：1.6K（A4，Coverage of 5%） ',
        },

        {
            _id: '12',
            name: 'Toner AR-CF353A',
            category: 'Tonner',
            image: '/images/p3.jpg',
            price: 2810,
            countInStock: 10,
            barnd: ' Arecolor Toner Cartridge',
            rating: 4.5,
            numReviews: 10,
            description: 'Brilliant white print outs, High Yield',
        },
        
       
        {
            _id: '13',
            name: 'Toner AR-Q5949A',
            category: 'Tonner',
            image: '/images/p013.jpg',
            price: 2570,
            countInStock: 40,
            barnd: 'Arecolor',
            rating: 4.5,
            numReviews: 10,
            description: 'Colour: Black, Page Yield:2500 pages,  ',
        },

        {
            _id: '14',
            name: 'Toner AR-Q2612A',
            category: 'Tonner',
            image: '/images/p4.jpg',
            price: 700,
            countInStock: 20,
            barnd: '',
            rating: 4.5,
            numReviews: 10,
            description: 'Brand: Printmate, Colour:Black, Page Yield:2000 pages, Replaces HP Q2612A, Compatible with HP 1010/1012/1015/1018/1020/1022/3015/3020/3030/3050/3052/3055/M1005/M1319F  ',
        },

        
        
        {
            _id: '15',
            name: 'Toner AR-Q6511A',
            category: 'Shirt',
            image: '/images/p15.jpg',
            price: 4770,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },

        {
            _id: '16',
            name: 'Toner AR-Q2613A /C7115A',
            category: 'Tonner',
            image: '/images/p16.jpg',
            price: 3700,
            countInStock: 40,
            barnd: '',
            rating: 4.5,
            numReviews: 10,
            description: 'Compatible Toner AR-Q2613A /C7115A',
        },
        {
            _id: '17',
            name: 'HP CF540A 203A Black Toner Cartridge',
            category: 'Toner',
            image: '/images/p17.jpg',
            price: 8900,
            countInStock: 40,
            barnd: '',
            rating: 4.5,
            numReviews: 10,
            description: 'Cartridge Colors: Black, Print Technology: Laser, Product type: Standard Capacity Toner Cartridges, Yield: 1400pages',
        },
        {
            _id: '18',
            name: 'AR-CF540A 203A',
            category: 'Toners',
            image: '/images/p18.jpg',
            price: 5310,
            countInStock: 16,
            barnd: '',
            rating: 4.,
            numReviews: 18,
            description: 'high quality product, Compatible Toner AR-CF540A 203A',
        },
        {
            _id: '19',
            name: 'Toner AR-CF543A 203A',
            category: 'Toner',
            image: '/images/p19.jpg',
            price: 6200,
            countInStock: 4,
            barnd: 'Nike',
            rating: 7.5,
            numReviews: 3,
            description: 'high quality product',
        },


        {
            _id: '20',
            name: 'HP CF541A 203A Cyan Toner Cartridge',
            category: 'Shirt',
            image: '/images/p20.jpg',
            price: 9950,
            countInStock: 40,
            barnd: '',
            rating: 4.5,
            numReviews: 13,
            description: 'Get high-quality prints and performance from your printer or MFP. Original HP Toner cartridges with JetIntelligence match your printer’s high-speeds and increase efficiency. Go with toner that works best with your printer – Original HP.',
        },
        {
            _id: '21',
            name: 'Toner AR-CF541A 203A',
            category: 'Tonners',
            image: '/images/p21.jpg',
            price: 5990,
            countInStock: 40,
            barnd: '',
            rating: 6.5,
            numReviews: 12,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 1900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 1900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },


        {
            _id: '6',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 1900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 1900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 1900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 1900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },


        {
            _id: '6',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 1900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 1900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 1900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 1900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },

        {
            _id: '6',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 1900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 1900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 1900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 1900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },


        {
            _id: '6',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 1900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 1900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 1900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 1900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
    ],

};

export default data;