const data = {
    products:[
        {
            _id: '1',
            name: 'Toner AR-CE285A',
            category: 'Tonner',
            image: '/images/p1.jpg',
            price: 1620,
            countInStock: 0,
            barnd: '',
            rating: 4.5,
            numReviews: 10,
            description: 'Page Yield:1600, FOR USE IN: HP LasterJet Pro P1102/P1102W M1132/M1212nf/1214nfh/1217nfw',
        },

        {
            _id: '2',
            name: 'Toner AR-CB436A',
            category: 'Tonner',
            image: '/images/p5.jpg',
            price: 2450,
            countInStock: 30,
            barnd: 'Arecolor',
            rating: 4.5,
            numReviews: 10,
            description: 'Color: Black,  Page Yield: 2000 pages,    Replaces HP CB436A, Briliant printouts ',
        },

        {
            _id: '3',
            name: 'Toner AR-CE285A',
            category: 'Tonner',
            image: '/images/p12.jpg',
            price: 1620,
            countInStock: 40,
            barnd: '',
            rating: 6.5,
            numReviews: 10,
            description: 'Page Yield:1600, FOR USE IN: HP LasterJet Pro P1102/P1102W M1132/M1212nf/1214nfh/1217nfw',
        },


        {
            _id: '4',
            name: 'Toner AR-Q7551A',
            category: 'Toner',
            image: '/images/p14.jpg',
            price: 1920,
            countInStock: 40,
            barnd: '',
            rating: 4.5,
            numReviews: 17,
            description: 'high quality product',
        },

       
        
        {
            _id: '5',
            name: 'Toner AR-Q2612A',
            category: 'Tonner',
            image: '/images/p2.jpg',
            price: 700,
            countInStock: 60,
            barnd: '',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product',
        },
        
        {
            _id: '6',
            name: 'Toner AR-CE505A',
            category: 'Toner',
            image: '/images/p6.jpg',
            price: 2080,
            countInStock: 4,
            barnd: '',
            rating: 4.5,
            numReviews: 6,
            description: 'HP Series AR-CE505A, OEM Model: CE505A, Color: black,FOR USE IN HP P2035/2035/2055N',
        },

        {
            _id: '7',
            name: 'Toner AR-CF280A',
            category: 'Tonner',
            image: '/images/p6.jpg',
            price: 2980,
            countInStock: 40,
            barnd: ': Arecolor',
            rating: 4.5,
            numReviews: 10,
            description: 'Colour:Black, Page Yield:2,700/6,900 (5%,A4), Replaces Hp CF 280A, Compatible with HP Laserjet pro M401d/M401n/M401dn/M401dw/MFP M425f/M425dn/M425dw ',
        },

        {
            _id: '8',
            name: 'HP toner CF287A',
            category: 'Toners',
            image: '/images/p8.jpg',
            price: '2100',
            countInStock: 40,
            barnd: 'Nike',
            rating: 6.5,
            numReviews:18,
            description: 'HP toner CF287A, Cartridge Colors: Black, Print Technology: Laser, Page yield: 8550,  Product type: Standard Capacity Toner Cartridges, HP LaserJet Enterprise M506 Printer series, HP LaserJet Enterprise MFP M527 series ',
        },
        {
            _id: '9',
            name: 'HP toner CF226A',
            category: 'Toners',
            image: '/images/p9.jpg',
            price: 15500,
            countInStock: 4,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'HP 26A black toner cartridge, CF226A produces superior quality and consistency for a wide array of printing needs, color Black, Yields up to 3,100 pages',
        },
        {
            _id: '10',
            name: 'HP Toner CF217A Black',
            category: 'Tonner',
            image: '/images/p10.jpg',
            price: 8600,
            countInStock: 40,
            barnd: 'hp',
            rating: 4.5,
            numReviews: 10,
            description: 'color: black, Print technology: laser, Approximate average yield based on ISO/IEC 19752. Actual yield varies considerably based on content of printed pages and other factors. ',
        },
        {
            _id: '11',
            name: 'Toner AR-CF230A',
            category: 'Toner',
            image: '/images/p11.jpg',
            price: 3470,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'HP Series AR-CF230A, OEM Model:CF230A, Color: Black, FOR USE IN: HP LaserJet M203d/203dn/203dw/M227fdn/227fdw, Page Yield ：1.6K（A4，Coverage of 5%） ',
        },

        {
            _id: '12',
            name: 'Toner AR-CF353A',
            category: 'Tonner',
            image: '/images/p3.jpg',
            price: 2810,
            countInStock: 10,
            barnd: ' Arecolor Toner Cartridge',
            rating: 4.5,
            numReviews: 10,
            description: 'Brilliant white print outs, High Yield',
        },
        
       
        {
            _id: '13',
            name: 'Toner AR-Q5949A',
            category: 'Tonner',
            image: '/images/p013.jpg',
            price: 2570,
            countInStock: 40,
            barnd: 'Arecolor',
            rating: 4.5,
            numReviews: 10,
            description: 'Colour: Black, Page Yield:2500 pages,  ',
        },

        {
            _id: '14',
            name: 'Toner AR-Q2612A',
            category: 'Tonner',
            image: '/images/p4.jpg',
            price: 700,
            countInStock: 20,
            barnd: '',
            rating: 4.5,
            numReviews: 10,
            description: 'Brand: Printmate, Colour:Black, Page Yield:2000 pages, Replaces HP Q2612A, Compatible with HP 1010/1012/1015/1018/1020/1022/3015/3020/3030/3050/3052/3055/M1005/M1319F  ',
        },

        
        
        {
            _id: '15',
            name: 'Toner AR-Q6511A',
            category: 'Shirt',
            image: '/images/p15.jpg',
            price: 4770,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },

        {
            _id: '16',
            name: 'Toner AR-Q2613A /C7115A',
            category: 'Tonner',
            image: '/images/p16.jpg',
            price: 3700,
            countInStock: 40,
            barnd: '',
            rating: 4.5,
            numReviews: 10,
            description: 'Compatible Toner AR-Q2613A /C7115A',
        },
        {
            _id: '17',
            name: 'HP CF540A 203A Black Toner Cartridge',
            category: 'Toner',
            image: '/images/p17.jpg',
            price: 8900,
            countInStock: 40,
            barnd: '',
            rating: 4.5,
            numReviews: 10,
            description: 'Cartridge Colors: Black, Print Technology: Laser, Product type: Standard Capacity Toner Cartridges, Yield: 1400pages',
        },
        {
            _id: '18',
            name: 'AR-CF540A 203A',
            category: 'Toners',
            image: '/images/p18.jpg',
            price: 5310,
            countInStock: 16,
            barnd: '',
            rating: 4.,
            numReviews: 18,
            description: 'high quality product, Compatible Toner AR-CF540A 203A',
        },
        {
            _id: '19',
            name: 'Toner AR-CF543A 203A',
            category: 'Toner',
            image: '/images/p19.jpg',
            price: 6200,
            countInStock: 4,
            barnd: 'Nike',
            rating: 7.5,
            numReviews: 3,
            description: 'high quality product',
        },


        {
            _id: '20',
            name: 'HP CF541A 203A Cyan Toner Cartridge',
            category: 'Shirt',
            image: '/images/p20.jpg',
            price: 9950,
            countInStock: 40,
            barnd: '',
            rating: 4.5,
            numReviews: 13,
            description: 'Get high-quality prints and performance from your printer or MFP. Original HP Toner cartridges with JetIntelligence match your printer’s high-speeds and increase efficiency. Go with toner that works best with your printer – Original HP.',
        },
        {
            _id: '21',
            name: 'Toner AR-CF541A 203A',
            category: 'Tonners',
            image: '/images/p21.jpg',
            price: 5990,
            countInStock: 40,
            barnd: '',
            rating: 6.5,
            numReviews: 12,
            description: 'high quality product',
        },
        {
            _id: '22',
            name: 'HP CF542A 203A Yellow Toner Cartridge',
            category: 'Toners',
            image: '/images/p22.jpg',
            price: 9950,
            countInStock: 15,
            barnd: '',
            rating: 5.5,
            numReviews: 10,
            description: 'Color(s) of printing supplies: Yellow, Compatibility: HP Color LaserJet Pro M254dw(T6B60A), HP Color LaserJet Pro M254nw(T6B59A), HP Color LaserJet Pro MFP M280nw(T6B80A), HP Color LaserJet Pro MFP M281fdn(T6B81A), HP Color LaserJet Pro MFP M281fdw(T6B82A), Page yield footnote: Approximate average composite cyan, yellow, magenta yield based on ISO/IEC 19798. Actual yield varies considerably based on content of printed pages and other factor, Print technology: Laser  ',
        },
        {
            _id: '23',
            name: ' Toner AR-CF542A 203A',
            category: 'Toners',
            image: '/images/p23.jpg',
            price: 6200,
            countInStock: 5,
            barnd: '',
            rating: 4.5,
            numReviews: 10,
            description: 'Toner AR-CF542A 203A',
        },


        {
            _id: '24',
            name: 'Toner AR-CF543A 203A',
            category: 'Toner',
            image: '/images/p24.jpg',
            price: 6200,
            countInStock: 40,
            barnd: '',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '25',
            name: 'HP CF543A 203A',
            category: 'Toners',
            image: '/images/p25.jpg',
            price: 9950,
            countInStock: 40,
            barnd: '',
            rating: 4.5,
            numReviews: 10,
            description: 'Get high-quality prints and performance from your printer or MFP. Original HP Toner cartridges with JetIntelligence match your printer’s high-speeds and increase efficiency. Go with toner that works best with your printer – Original HP.',
        },
        {
            _id: '26',
            name: 'Toner AR-CF543A 203A',
            category: 'Toner',
            image: '/images/p26.jpg',
            price: 6200,
            countInStock: 12,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 13,
            description: 'high quality product, Compatible Toner AR-CF543A 203A',
        },
        {
            _id: '27',
            name: 'Toner AR-CF411A',
            category: 'Tonner',
            image: '/images/p6.jpg',
            price: 4500,
            countInStock: 18,
            barnd: '',
            rating: 4.5,
            numReviews: 10,
            description: 'Compatible with HP Series AR-CF411A, OEM Model:HP CF411A(410A), Color: Cyan, FOR USE IN:  HP Color LaserJet M452DN/M452DW/M452NW/MFP M477fdn/M477fdw/M477fnw',
        },


        {
            _id: '28',
            name: 'Toner AR-CF412A',
            category: 'Toner',
            image: '/images/p6.jpg',
            price: 4520,
            countInStock: 40,
            barnd: 'Arecolor',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product,  Colour:yellow, Page Yield:2,700/6,900 (5%,A4), Replaces Hp CF 280A',
        },
        {
            _id: '29',
            name: 'Toner AR-CF413A',
            category: 'Toner',
            image: '/images/p6.jpg',
            price: 4660,
            countInStock: 40,
            barnd: 'Printmate',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product, Colour:Black,  Page Yield:2,300/5,000 (5%,A4),  Brilliant white print outs ',
        },
        {
            _id: '30',
            name: 'Toner AR-CF210A (131A)',
            category: 'Toner',
            image: '/images/p6.jpg',
            price: 3180,
            countInStock: 40,
            barnd: 'Arecolor',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product, Page Yield: 1,600/2,400 (5%,A4), Compatible with HP pro color M251n/M251nw/MFP M276n/M276nw',
        },
        {
            _id: '31',
            name: 'Toner AR-CF210A (131A',
            category: 'Toners',
            image: '/images/p6.jpg',
            price: 3180,
            countInStock: 21,
            barnd: 'Arecolor',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product, Colour:Black, Page Yield: 1,600/2,400 (5%,A4), Compatible with HP pro color M251n/M251nw/MFP M276n/M276nw ',
        },

        {
            _id: '32',
            name: 'Toner AR-CF217A',
            category: 'Toner',
            image: '/images/p6.jpg',
            price: 2910,
            countInStock: 4,
            barnd: '',
            rating: 4.5,
            numReviews: 10,
            description: 'HP LaserJet Pro MFP M130fn/M102w/M130fw, Page Yield ：1.6K（A4，Coverage of 5%）',
        },
        {
            _id: '33',
            name: 'Toner AR-CF211A (131A)',
            category: 'Toner',
            image: '/images/p33.jpg',
            price: 3540,
            countInStock: 40,
            barnd: 'Arecolor ',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product, Colour:Cyan, Page Yield: 1800 (5%,A4) , Compatible with HP pro color M251n/M251nw/MFP M276n/M276nw',
        },
        {
            _id: '34',
            name: 'Toner AR-CF212A (131A)',
            category: 'Toner',
            image: '/images/p34.jpg',
            price: 3590,
            countInStock: 4,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product, Colour:Yellow, Page Yield:  1800  (5%,A4), Compatible with HP Laserjet pro color M251n/M251nw/MFP M276n/M276nw',
        },
        {
            _id: '35',
            name: ' Arecolor Toner Cartridge AR-CF350A(130A)',
            category: 'Arecolor',
            image: '/images/p6.jpg',
            price: 3150,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },


        {
            _id: '36',
            name: 'Toner AR-CF351A',
            category: 'Shirt',
            image: '/images/p36.jpg',
            price: 3160,
            countInStock: 4,
            barnd: 'Arecolor',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product, Colour:Cyan, Page Yield: 1,000  (5%,A4) , Compatible with HP Laserjet pro MFP M176n/M177fw ',
        },
        {
            _id: '37',
            name: 'Hp Toner Cartridge CF351A Cyan',
            category: 'Shirt',
            image: '/images/p37.jpg',
            price: 7900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'Supply Type: TonerInk/Toner Color: CyanPage Yield Per Package (Up to): 1,000Ink/Toner Pack Size: 1/PackCartridge Yield Type: StandardWide Format Compatibility: NoInk/Toner Cartridge Type: Original',
        },
        {
            _id: '38',
            name: ' Toner AR-CF352A',
            category: 'Toner',
            image: '/images/p6.jpg',
            price: 2470,
            countInStock: 40,
            barnd: ' Arecolor',
            rating: 4.5,
            numReviews: 10,
            description: 'Colour:Yellow, Page Yield: 1,000  (5%,A4)  , Compatible with HP M176n/M177fw',
        },
        {
            _id: '39',
            name: 'Hp Toner Cartridge CF352A',
            category: 'Toner',
            image: '/images/p39.jpg',
            price: 8900,
            countInStock: 40,
            barnd: '',
            rating: 4.5,
            numReviews: 10,
            description: 'Supply Type TonerInk/Toner Color YellowPage Yield Per Package (Up to) 1,000Ink/Toner Pack Size 1/PackCartridge Yield Type StandardWide Format Compatibility NoInk/Toner Cartridge Type Original',
        },

        {
            _id: '40',
            name: 'Hp Toner Cartridge CF352A',
            category: 'Toner',
            image: '/images/p40.jpg',
            price: 7900,
            countInStock: 40,
            barnd: '',
            rating: 4.5,
            numReviews: 10,
            description: 'Supply Type TonerInk/Toner Color YellowPage Yield Per Package (Up to) 1,000Ink/Toner Pack Size 1/PackCartridge Yield Type StandardWide Format Compatibility NoInk/Toner Cartridge Type Original',
        },

        {
            _id: '41',
            name: 'Toner AR-CF353A',
            category: 'Toner',
            image: '/images/p6.jpg',
            price: 2810,
            countInStock: 40,
            barnd: 'Brand: Arecolor Toner Cartridge',
            rating: 4.5,
            numReviews: 10,
            description: 'Brilliant white print outs',
        },

        {
            _id: '42',
            name: 'Toner AR-CE310A (126A)',
            category: 'Toner',
            image: '/images/p42.jpg',
            price: 8900,
            countInStock: 40,
            barnd: 'Arecolor',
            rating: 4.5,
            numReviews: 10,
            description: 'color black, Compatible with HP pro color CP 1025/1025NW/MFPVM175NW/M275',
        },
        {
            _id: '43',
            name: ' Toner AR-CE311A ',
            category: 'Toner',
            image: '/images/p43.jpg',
            price: 2110,
            countInStock: 40,
            barnd: ' Arecolor',
            rating: 4.5,
            numReviews: 10,
            description: ' color: Cyan, Page Yield: 1000 (5%,A4), Compatible with HP CP 1025/1025NW/MFPVM175NW/M275 ',
        },

        {
            _id: '44',
            name: 'Arecolor Toner Cartridge AR-CE312A',
            category: 'Toner',
            image: '/images/p6.jpg',
            price: 3100,
            countInStock: 40,
            barnd: '',
            rating: 4.5,
            numReviews: 10,
            description: 'Supply Type TonerInk/Toner Color YellowPage Yield Per Package (Up to) 1,000Ink/Toner Pack Size 1/PackCartridge Yield Type StandardWide Format Compatibility NoInk/Toner Cartridge Type Original',
        },

        {
            _id: '45',
            name: 'Toner Cartridge AR-CE313A',
            category: 'Toner',
            image: '/images/p45.jpg',
            price: 25100,
            countInStock: 4,
            barnd: 'Arecolor',
            rating: 4.5,
            numReviews: 10,
            description: 'Colour:Magenta, Page Yield: 1000 (5%,A4), Compatible with HP CP 1025/1025NW/MFPVM175NW/M275 ',
        },
        {
            _id: '46',
            name: 'Toner Cartridge AR-CF350A/CE310A',
            category: 'Toner',
            image: '/images/p6.jpg',
            price: 3150,
            countInStock: 40,
            barnd: '',
            rating: 4.5,
            numReviews: 10,
            description: 'High Product',
        },
        {
            _id: '47',
            name: 'Toner Cartridge AR-CF352A/CE312A',
            category: 'Toner',
            image: '/images/p6.jpg',
            price: 3100,
            countInStock: 40,
            barnd: '',
            rating: 4.5,
            numReviews: 10,
            description: 'Toner Cartridge AR-CF352A/CE312A',
        },
        {
            _id: '48',
            name: 'Toner AR-CE410A (305A)',
            category: 'Toner',
            image: '/images/p48.jpg',
            price: 4750,
            countInStock: 40,
            barnd: 'Arecolor',
            rating: 4.5,
            numReviews: 10,
            description: ' color: black, Compatible with HP pro color M351a/M451dn/M451nw/MFP M375nw/M475dn/M475dn/M475dw',
        },
        {
            _id: '49',
            name: 'Hp Toner Cartridge CF352A',
            category: 'Toner',
            image: '/images/p49.jpg',
            price: 4250,
            countInStock: 40,
            barnd: '',
            rating: 4.5,
            numReviews: 10,
            description: ' color -cyan, for use in -HP LaserJet Pro Color M351a/M451dnM451dw/M451nw/MFP M375nw/M475dn/M475dw2.6K（A4，Coverage of 5%）',
        },

        {
            _id: '50',
            name: 'Toner AR-CE412A ',
            category: 'Toner',
            image: '/images/p50.jpg',
            price: 4450,
            countInStock: 40,
            barnd: '',
            rating: 4.5,
            numReviews: 10,
            description: ' color: Yellow, Page Yield: 2600  (5%,A4) , Compatible with HP Laserjet pro color M351a/M451dn/M451nw/MFP M375nw/M475d ',
        },
        {
            _id: '51',
            name: 'Hp Toner Cartridge CF352A',
            category: 'Toner',
            image: '/images/p6.jpg',
            price: 3980,
            countInStock: 40,
            barnd: '',
            rating: 4.5,
            numReviews: 10,
            description: 'Compatible with HP Laserjet pro M351a/M451dn/M451nw/MFP M375nw/M475dn/M4',
        },
        {
            _id: '52',
            name: 'Hp Toner Cartridge CF352A',
            category: 'Toner',
            image: '/images/p39.jpg',
            price: 4670,
            countInStock: 40,
            barnd: '',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality product',
        },
        {
            _id: '53',
            name: 'Hp Toner Cartridge CF352A',
            category: 'Toner',
            image: '/images/p53.jpg',
            price: 49200,
            countInStock: 40,
            barnd: '',
            rating: 4.5,
            numReviews: 10,
            description: ' high quality product',
        },
        {
            _id: '54',
            name: ' Toner AR-CF381A ',
            category: 'Toner',
            image: '/images/p54.jpg',
            price: 5930,
            countInStock: 40,
            barnd: '',
            rating: 4.5,
            numReviews: 10,
            description: ' High quality product',
        },
        {
            _id: '55',
            name: 'Toner AR-CF381A',
            category: 'Toner',
            image: '/images/p55.jpg',
            price: 4930,
            countInStock: 40,
            barnd: '',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality product',
        },
        {
            _id: '56',
            name: ' Toner AR-CB540A (125A)',
            category: 'Toner',
            image: '/images/p56.jpg',
            price: 4440,
            countInStock: 40,
            barnd: '',
            rating: 4.5,
            numReviews: 10,
            description: 'HP Laserjet CP 1215/CP1515N/CP1518NICM 1312NFI/CMI/1312MFP',
        },
        {
            _id: '57',
            name: ' Toner AR-CB541A ',
            category: 'Toner',
            image: '/images/p57.jpg',
            price: 4350,
            countInStock: 40,
            barnd: '',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality Product',
        },
        {
            _id: '58',
            name: 'Hp Toner Cartridge CF352A',
            category: 'Toner',
            image: '/images/p58.jpg',
            price: 4290,
            countInStock: 40,
            barnd: '',
            rating: 4.5,
            numReviews: 10,
            description: ' High Quality prduct',
        },
        {
            _id: '59',
            name: 'Arecolor Toner Cartridge AR-CE322A',
            category: 'Toner',
            image: '/images/p59.jpg',
            price: 4290,
            countInStock: 4,
            barnd: '',
            rating: 4.5,
            numReviews: 11,
            description: 'High quality product',
        },
        {
            _id: '60',
            name: ' Toner AR-CB543A',
            category: 'Toner',
            image: '/images/p60.jpg',
            price: 4390,
            countInStock: 40,
            barnd: '',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality product ',
        },
        {
            _id: '61',
            name: 'Toner AR-CE320A',
            category: 'Toner',
            image: '/images/p6.jpg',
            price: 36400,
            countInStock: 4,
            barnd: '',
            rating: 4.5,
            numReviews: 10,
            description: 'Color:Black, FOR USE IN: HP Color LaserJet Pro CP 1525N/1525NW/CM1415/1415FN/1415FNW, Page Yield: 2K A4 (Coverage of 5%)',
        },
        {
            _id: '62',
            name: ' Toner AR-CE321A ',
            category: 'Toner',
            image: '/images/p62.jpg',
            price: 3880,
            countInStock: 2,
            barnd: 'Arecolor ',
            rating: 4.5,
            numReviews: 16,
            description: 'Colour:Cyan, Page Yield: 1300 (5%,A4) , Compatible with HP pro CP1525N/1525NW/CM1415/1415FN/1415FNW ',
        },
        {
            _id: '63',
            name: 'Toner AR-CE323A ',
            category: 'Toner',
            image: '/images/p63.jpg',
            price: 3860,
            countInStock: 7,
            barnd: 'Arecolor',
            rating: 6.5,
            numReviews: 10,
            description: 'Page Yield:  1300 (5%,A4)  ,  Compatible with HP CP1525N/1525NW/CM1415/1415FN/1415FNW',
        },
        {
            _id: '64',
            name: 'Toner AR-Q6001A',
            category: 'Toner',
            image: '/images/p64.jpg',
            price: 4810,
            countInStock: 40,
            barnd: '',
            rating: 4.5,
            numReviews: 10,
            description: ' High Qulity product',
        },

        {
            _id: '65',
            name: 'Toner AR-Q6001A',
            category: 'Toner',
            image: '/images/p65.jpg',
            price: 4810,
            countInStock: 40,
            barnd: '',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality product',
        },
        {
            _id: '66',
            name: 'Hp Toner Cartridge CF352A',
            category: 'Toner',
            image: '/images/p66.jpg',
            price: 48100,
            countInStock: 40,
            barnd: '',
            rating: 4.5,
            numReviews: 10,
            description: ' High quality Product',
        },
        {
            _id: '67',
            name: ' Toner AR-Q6003A',
            category: 'Toner',
            image: '/images/p67.jpg',
            price: 4810,
            countInStock: 3,
            barnd: '',
            rating: 4.5,
            numReviews: 10,
            description: ' High quality product',
        },

        {
            _id: '68',
            name: 'hp ink',
            category: 'Ink',
            image: '/images/p68.jpg',
            price: 2700,
            countInStock: 40,
            barnd: '',
            rating: 4.5,
            numReviews: 10,
            description: 'Print vivid colour documents that resist fading, with Original HP inks. See fine details in images and photos  ink cartridge technology delivers an extremely small drop size. Photos dry instantly when you use HP Advanced Photo Paper.Enjoy user-friendly features and an affordable price. Monitor ink levels with included ink-level gauge and finish critical print jobs when a specific ink is low. Its easy to choose the Original HP ink cartridge tailored to fit your printing needs.',
        },

        {
            _id: '69',
            name: 'HP Ink Cartridge 951 M XL',
            category: 'Ink',
            image: '/images/p69.jpg',
            price: 3950,
            countInStock: 40,
            barnd: '',
            rating: 4.5,
            numReviews: 10,
            description: 'Product DescriptionAll genuine Hewlett Packard color inkjet cartridges are designed to produce remarkable image quality and vivid colors. The genuine HP 951XL high yield magenta printer ink cartridge delivers dazzling color and yields up to 1500 pages. ',
        },

        {
            _id: '70',
            name: 'HP Ink Cartridge 951 Y XL',
            category: 'Ink',
            image: '/images/p70.jpg',
            price: 3950,
            countInStock: 40,
            barnd: '',
            rating: 4.5,
            numReviews: 10,
            description: 'Print professional color page after page, and save compared with laser printers. Bring documents and marketing materials to life with outstanding color vibrancy for a low cost per page, and easily recycle your cartridges.Want more pages, great reliability, and amazing value? You want original HP inks, Color(s) of print cartridges-Yellow, Page yield (colour)-1,500 pages ',
        },

        {
            _id: '71',
            name: 'HP Ink Cartridge 951 M XL',
            category: 'Ink',
            image: '/images/p71.jpg',
            price: 3950,
            countInStock: 40,
            barnd: '',
            rating: 4.5,
            numReviews: 10,
            description: ' HP Deskjet Ink Advantage 2515',
        },


        {
            _id: '72',
            name: 'HP Ink Cartridge 951 C XL',
            category: 'Ink',
            image: '/images/p72.jpg',
            price: 3950,
            countInStock: 40,
            barnd: '',
            rating: 4.5,
            numReviews: 10,
            description: 'Yield of 1,500 pages, Compatible with: Office jet Pro 8600 E-All-in-One, Office jet Pro 8600 Plus E-All-in-One and Office jet Pro 8100 E Printer ',
        },

        {
            _id: '69',
            name: 'HP Ink Cartridge 951 M XL',
            category: 'Ink',
            image: '/images/p69.jpg',
            price: 3950,
            countInStock: 40,
            barnd: '',
            rating: 4.5,
            numReviews: 10,
            description: ' HP Deskjet Ink Advantage 2515',
        },


        {
            _id: '69',
            name: 'HP Ink Cartridge 951 M XL',
            category: 'Ink',
            image: '/images/p69.jpg',
            price: 3950,
            countInStock: 40,
            barnd: '',
            rating: 4.5,
            numReviews: 10,
            description: ' HP Deskjet Ink Advantage 2515',
        },


        {
            _id: '69',
            name: 'HP Ink Cartridge 951 M XL',
            category: 'Ink',
            image: '/images/p69.jpg',
            price: 3950,
            countInStock: 40,
            barnd: '',
            rating: 4.5,
            numReviews: 10,
            description: ' HP Deskjet Ink Advantage 2515',
        },


        {
            _id: '69',
            name: 'HP Ink Cartridge 951 M XL',
            category: 'Ink',
            image: '/images/p69.jpg',
            price: 3950,
            countInStock: 40,
            barnd: '',
            rating: 4.5,
            numReviews: 10,
            description: ' HP Deskjet Ink Advantage 2515',
        },


        {
            _id: '69',
            name: 'HP Ink Cartridge 951 M XL',
            category: 'Ink',
            image: '/images/p69.jpg',
            price: 3950,
            countInStock: 40,
            barnd: '',
            rating: 4.5,
            numReviews: 10,
            description: ' HP Deskjet Ink Advantage 2515',
        },
    ],

};

export default data;