const data = {
    products:[
        {
            _id: '1',
            name: 'Nike slime shirt',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 1900,
            countInStock: 0,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },

        {
            _id: '2',
            name: 'Adidas Fit shirt',
            category: 'Shirts',
            image: '/images/p2.jpg',
            price: 200,
            countInStock: 60,
            barnd: 'Adidas',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'Lacoste shirt',
            category: 'Shirts',
            image: '/images/p3.jpg',
            price: 1400,
            countInStock: 10,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: 'Puma slime shirt',
            category: 'Shirt',
            image: '/images/p4.jpg',
            price: 1900,
            countInStock: 20,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '5',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p5.jpg',
            price: 1900,
            countInStock: 30,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 1900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },

        {
            _id: '6',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 1900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },

        {
            _id: '6',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 1900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 1900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 1900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 1900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 1900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },

        {
            _id: '6',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 1900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 1900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 1900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 1900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },

        {
            _id: '6',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 1900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 1900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 1900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 1900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },


        {
            _id: '6',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 1900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 1900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 1900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 1900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },


        {
            _id: '6',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 1900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 1900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 1900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 1900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },


        {
            _id: '6',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 1900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 1900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 1900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 1900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },

        {
            _id: '6',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 1900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 1900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 1900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 1900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },


        {
            _id: '6',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 1900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 1900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 1900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Nike slime shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 1900,
            countInStock: 40,
            barnd: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
    ],

};

export default data;